package com.br.tecnomais.vconfiguracao2;

import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.classes.ValidarCamposNumericos;
import com.br.tecnomais.dao.OperacaoDAO;
import com.br.tecnomais.entity.OperacaoEntity;
import com.br.tecnomais.vconfiguracao.FixedLengthDocument;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Diherllys e DuDu
 */
public class OperacaoView extends javax.swing.JFrame {

    Alertas alerta = new Alertas();
    OperacaoEntity operacaoEntity;

    /**
     * Creates new form OperacaoView
     */
    public OperacaoView(OperacaoEntity ope, boolean campos) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.operacaoEntity = ope;
        limitarCampos();
        preencherCampos(campos);
        removerBotao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfNaturezaDaOp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbCaracDaOperação = new javax.swing.JComboBox();
        cbAumentarEstoque = new javax.swing.JCheckBox();
        cbDiminuiComissaoDeProdutos = new javax.swing.JCheckBox();
        cbDiminuiComissaoDeServicos = new javax.swing.JCheckBox();
        cbSaiDinheiroCaixaPagar = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel10.setBackground(new java.awt.Color(170, 180, 180));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Operação");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel10.setOpaque(true);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Natureza da Operação");

        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodigoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Características da Operação:");

        cbCaracDaOperação.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compra", "Compra de Produtos Consignados", "Consignação", "Devolução de Produtos Consignados", "Transferência", "Ajuste de Estoque" }));
        cbCaracDaOperação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaracDaOperaçãoActionPerformed(evt);
            }
        });

        cbAumentarEstoque.setBackground(new java.awt.Color(200, 210, 210));
        cbAumentarEstoque.setText("Aumentar Estoque");

        cbDiminuiComissaoDeProdutos.setBackground(new java.awt.Color(200, 210, 210));
        cbDiminuiComissaoDeProdutos.setText("Diminui Comissão de Produtos");

        cbDiminuiComissaoDeServicos.setBackground(new java.awt.Color(200, 210, 210));
        cbDiminuiComissaoDeServicos.setText("Diminui Comissão de Serviços");

        cbSaiDinheiroCaixaPagar.setBackground(new java.awt.Color(200, 210, 210));
        cbSaiDinheiroCaixaPagar.setText("Sai Dinheiro ( caixa / pagar)");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbCaracDaOperação, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDiminuiComissaoDeProdutos)
                                    .addComponent(cbAumentarEstoque))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSaiDinheiroCaixaPagar)
                                    .addComponent(cbDiminuiComissaoDeServicos))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfNaturezaDaOp)))
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRemover)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNaturezaDaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCaracDaOperação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAumentarEstoque)
                    .addComponent(cbSaiDinheiroCaixaPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDiminuiComissaoDeProdutos)
                    .addComponent(cbDiminuiComissaoDeServicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(bRemover))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbCaracDaOperaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaracDaOperaçãoActionPerformed
        selecionarBox();
    }//GEN-LAST:event_cbCaracDaOperaçãoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfId.getText().equals("")) {
            salvarOperacao();
        } else {
            alterarOperacao();
            limparCampos();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new PesquisaOperacaoView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        try {
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente remover esta operação de entrada?", "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
            if (opcao == JOptionPane.YES_OPTION) {
                removerOperacao();
                limparCampos();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bRemoverActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limparCampos();
        removerIdRemove();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyReleased
        new ValidarCamposNumericos().validar(tfCodigo);
    }//GEN-LAST:event_tfCodigoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacaoView(null, false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRemover;
    private javax.swing.JCheckBox cbAumentarEstoque;
    private javax.swing.JComboBox cbCaracDaOperação;
    private javax.swing.JCheckBox cbDiminuiComissaoDeProdutos;
    private javax.swing.JCheckBox cbDiminuiComissaoDeServicos;
    private javax.swing.JCheckBox cbSaiDinheiroCaixaPagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNaturezaDaOp;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
private void preencherCampos(boolean campos) {
        if (campos == true) {
            tfCodigo.setText(String.valueOf(operacaoEntity.getCodigo()));
            tfNome.setText(operacaoEntity.getNome());
            tfNaturezaDaOp.setText(operacaoEntity.getNatureza());
            tfId.setText(String.valueOf(operacaoEntity.getId()));

            cbCaracDaOperação.setSelectedItem(operacaoEntity.getCaracteristicaDeOperacao());
            selecionarBox();

            cbAumentarEstoque.setSelected(operacaoEntity.isAumentaEstq());
            cbSaiDinheiroCaixaPagar.setSelected(operacaoEntity.isSaiDinheiro());
            cbDiminuiComissaoDeProdutos.setSelected(operacaoEntity.isDimComiDeProd());
            cbDiminuiComissaoDeServicos.setSelected(operacaoEntity.isDimComiDeServ());

        }
    }

    private void selecionarBox() {
        if (cbCaracDaOperação.getSelectedItem() == "Compra") {
            cbAumentarEstoque.setSelected(true);
            cbDiminuiComissaoDeProdutos.setSelected(false);
            cbDiminuiComissaoDeServicos.setSelected(false);
            cbSaiDinheiroCaixaPagar.setSelected(false);

            cbAumentarEstoque.setEnabled(true);
            cbDiminuiComissaoDeProdutos.setEnabled(true);
            cbDiminuiComissaoDeServicos.setEnabled(true);
            cbSaiDinheiroCaixaPagar.setEnabled(true);
        }
        if (cbCaracDaOperação.getSelectedItem() == "Compra de Produtos Consignados") {
            cbAumentarEstoque.setSelected(false);
            cbDiminuiComissaoDeProdutos.setSelected(false);
            cbDiminuiComissaoDeServicos.setSelected(false);
            cbSaiDinheiroCaixaPagar.setSelected(false);

            cbAumentarEstoque.setEnabled(false);
            cbDiminuiComissaoDeProdutos.setEnabled(true);
            cbDiminuiComissaoDeServicos.setEnabled(true);
            cbSaiDinheiroCaixaPagar.setEnabled(true);

        }
        if (cbCaracDaOperação.getSelectedItem() == "Consignação") {

            cbAumentarEstoque.setSelected(true);
            cbDiminuiComissaoDeProdutos.setSelected(false);
            cbDiminuiComissaoDeServicos.setSelected(false);
            cbSaiDinheiroCaixaPagar.setSelected(true);

            cbAumentarEstoque.setEnabled(false);
            cbDiminuiComissaoDeProdutos.setEnabled(true);
            cbDiminuiComissaoDeServicos.setEnabled(true);
            cbSaiDinheiroCaixaPagar.setEnabled(false);
        }
        if (cbCaracDaOperação.getSelectedItem() == "Devolução de Produtos Consignados") {
            cbAumentarEstoque.setEnabled(false);
            cbAumentarEstoque.setSelected(true);
            cbDiminuiComissaoDeProdutos.setSelected(false);
            cbDiminuiComissaoDeServicos.setSelected(false);
            cbSaiDinheiroCaixaPagar.setSelected(false);

            cbAumentarEstoque.setEnabled(false);
            cbDiminuiComissaoDeProdutos.setEnabled(true);
            cbDiminuiComissaoDeServicos.setEnabled(true);
            cbSaiDinheiroCaixaPagar.setEnabled(true);

        }
        if (cbCaracDaOperação.getSelectedItem() == "Transferência") {
            cbAumentarEstoque.setSelected(false);
            cbDiminuiComissaoDeProdutos.setSelected(false);
            cbDiminuiComissaoDeServicos.setSelected(false);
            cbSaiDinheiroCaixaPagar.setSelected(false);

            cbAumentarEstoque.setEnabled(true);
            cbDiminuiComissaoDeProdutos.setEnabled(true);
            cbDiminuiComissaoDeServicos.setEnabled(true);
            cbSaiDinheiroCaixaPagar.setEnabled(true);

        }
        if (cbCaracDaOperação.getSelectedItem() == "Ajuste de Estoque") {
            cbAumentarEstoque.setSelected(false);
            cbDiminuiComissaoDeProdutos.setSelected(false);
            cbDiminuiComissaoDeServicos.setSelected(false);
            cbSaiDinheiroCaixaPagar.setSelected(false);

            cbAumentarEstoque.setEnabled(true);
            cbDiminuiComissaoDeProdutos.setEnabled(true);
            cbDiminuiComissaoDeServicos.setEnabled(true);
            cbSaiDinheiroCaixaPagar.setEnabled(true);

        }
    }

    private void salvarOperacao() {
        try {
            OperacaoDAO dao = new OperacaoDAO();
            if (dao.codigoExistente(Integer.parseInt(tfCodigo.getText())) == false) {
                OperacaoEntity oe = new OperacaoEntity();
                oe.setCodigo(Integer.parseInt(tfCodigo.getText()));
                oe.setNome(tfNome.getText());
                oe.setNatureza(tfNaturezaDaOp.getText());
                oe.setCaracteristicaDeOperacao(cbCaracDaOperação.getSelectedItem().toString());
                oe.setAumentaEstq(cbAumentarEstoque.isSelected());
                oe.setSaiDinheiro(cbSaiDinheiroCaixaPagar.isSelected());
                oe.setDimComiDeProd(cbDiminuiComissaoDeProdutos.isSelected());
                oe.setDimComiDeServ(cbDiminuiComissaoDeServicos.isSelected());

                dao.salvar(oe);
                alerta.mensagemConfirmacao("Operação cadastrada com sucesso!!!");
                limparCampos();
            } else {
                alerta.mensagemAviso("O código da operação já existe!!!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void alterarOperacao() {
        try {
            OperacaoDAO dao = new OperacaoDAO();
            OperacaoEntity oe = new OperacaoEntity();
            oe.setCodigo(Integer.parseInt(tfCodigo.getText()));
            oe.setNome(tfNome.getText());
            oe.setNatureza(tfNaturezaDaOp.getText());
            oe.setCaracteristicaDeOperacao(cbCaracDaOperação.getSelectedItem().toString());
            oe.setId(this.operacaoEntity.getId());
            oe.setAumentaEstq(cbAumentarEstoque.isSelected());
            oe.setSaiDinheiro(cbSaiDinheiroCaixaPagar.isSelected());
            oe.setDimComiDeProd(cbDiminuiComissaoDeProdutos.isSelected());
            oe.setDimComiDeServ(cbDiminuiComissaoDeServicos.isSelected());

            alerta.mensagemConfirmacao("Operação alterada com sucesso!!!");
            dao.alterar(oe);
            removerIdRemove();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void removerOperacao() throws SQLException {
        OperacaoDAO dao = new OperacaoDAO();
        dao.remover(operacaoEntity.getId());
        removerIdRemove();
    }

    private void removerBotao() {
        if (tfId.getText().equals("")) {
            bRemover.setVisible(false);
        }
        if (operacaoEntity.getId() != null) {
            tfCodigo.setEditable(false);
        }
        tfId.setVisible(false);
    }

    private void limparCampos() {
        tfNome.setText("");
        tfId.setText("");
        tfNaturezaDaOp.setText("");
        tfCodigo.setText("");
        operacaoEntity.setId(null);

        cbCaracDaOperação.setSelectedIndex(0);

        cbAumentarEstoque.setSelected(false);
        cbSaiDinheiroCaixaPagar.setSelected(false);
        cbDiminuiComissaoDeProdutos.setSelected(false);
        cbDiminuiComissaoDeServicos.setSelected(false);
    }

    public void removerIdRemove() {
        operacaoEntity.setId(0);
        bRemover.setVisible(false);
        tfCodigo.setEditable(true);
    }

    private void limitarCampos() {
        tfNome.setDocument(new FixedLengthDocument(53));
        tfNaturezaDaOp.setDocument(new FixedLengthDocument(70));
    }
}
