/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.vconfiguracao2;

import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.classes.ValidarCamposNumericos;
import com.br.tecnomais.dao.OperacaoDeSaidaDAO;
import com.br.tecnomais.entity.OperacaoDeSaidaEntity;
import com.br.tecnomais.vconfiguracao.FixedLengthDocument;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Desenvolvimento
 */
public class OperacaoDeSaidaView extends javax.swing.JFrame {

    Alertas alerta = new Alertas();
    OperacaoDeSaidaEntity operacaoDeSaidaEntity;

    public OperacaoDeSaidaView(OperacaoDeSaidaEntity ope, boolean campos) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.operacaoDeSaidaEntity = ope;
        selecionarBox();
        limitarCampos();
        preencherCampos(campos);
        removerBotao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfNaturezaDaOp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbCaracDaOperação = new javax.swing.JComboBox();
        cbDiminuirEstoque = new javax.swing.JCheckBox();
        cbEntraDinheiro = new javax.swing.JCheckBox();
        cbCalcComissaoDeServ = new javax.swing.JCheckBox();
        cbCalcComissaoDeProd = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel10.setBackground(new java.awt.Color(170, 180, 180));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Operação de Saida");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel10.setOpaque(true);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Natureza da Operação");

        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodigoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Características da Operação:");

        cbCaracDaOperação.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Venda", "Pré Venda", "Ajuste de Saída", "Orçamento de Venda", "Saída Grátis" }));
        cbCaracDaOperação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaracDaOperaçãoActionPerformed(evt);
            }
        });

        cbDiminuirEstoque.setBackground(new java.awt.Color(200, 210, 210));
        cbDiminuirEstoque.setText("Diminuir Estoque");

        cbEntraDinheiro.setBackground(new java.awt.Color(200, 210, 210));
        cbEntraDinheiro.setText("Entra Dinheiro");

        cbCalcComissaoDeServ.setBackground(new java.awt.Color(200, 210, 210));
        cbCalcComissaoDeServ.setText("Calcula Comissão de Serviços");

        cbCalcComissaoDeProd.setBackground(new java.awt.Color(200, 210, 210));
        cbCalcComissaoDeProd.setText("Calcula Comissão de Produtos");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbCaracDaOperação, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEntraDinheiro)
                                    .addComponent(cbDiminuirEstoque))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCalcComissaoDeProd)
                                    .addComponent(cbCalcComissaoDeServ))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfNaturezaDaOp)))
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNaturezaDaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCaracDaOperação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDiminuirEstoque)
                    .addComponent(cbCalcComissaoDeProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEntraDinheiro)
                    .addComponent(cbCalcComissaoDeServ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(bRemover))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbCaracDaOperaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaracDaOperaçãoActionPerformed
        selecionarBox();
    }//GEN-LAST:event_cbCaracDaOperaçãoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfId.getText().equals("")) {
            salvarOperacao();
        } else {
            alterarOperacao();
            limparCampos();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new PesquisaOperacaoSaidaView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        try {
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente remover esta operação de saida?", "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
            if (opcao == JOptionPane.YES_OPTION) {
                if (!tfId.getText().equals("")) {
                    removerOperacao();
                    limparCampos();
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bRemoverActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limparCampos();
        removerIdRemove();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyReleased
        new ValidarCamposNumericos().validar(tfCodigo);
    }//GEN-LAST:event_tfCodigoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacaoDeSaidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacaoDeSaidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacaoDeSaidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacaoDeSaidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacaoDeSaidaView(null, false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRemover;
    private javax.swing.JCheckBox cbCalcComissaoDeProd;
    private javax.swing.JCheckBox cbCalcComissaoDeServ;
    private javax.swing.JComboBox cbCaracDaOperação;
    private javax.swing.JCheckBox cbDiminuirEstoque;
    private javax.swing.JCheckBox cbEntraDinheiro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNaturezaDaOp;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
private void preencherCampos(boolean campos) {
        if (campos == true) {
            tfCodigo.setText(String.valueOf(operacaoDeSaidaEntity.getCodigo()));
            tfNome.setText(operacaoDeSaidaEntity.getNome());
            tfNaturezaDaOp.setText(operacaoDeSaidaEntity.getNaturezaDaOperacao());
            cbCaracDaOperação.setSelectedItem(operacaoDeSaidaEntity.getCaracteristicaDeOperacao());
            tfId.setText(String.valueOf(operacaoDeSaidaEntity.getId()));
            selecionarBox();

            cbDiminuirEstoque.setSelected(operacaoDeSaidaEntity.isDimEstq());
            cbEntraDinheiro.setSelected(operacaoDeSaidaEntity.isEntraDinheiro());
            cbCalcComissaoDeProd.setSelected(operacaoDeSaidaEntity.isCalcComissProd());
            cbCalcComissaoDeServ.setSelected(operacaoDeSaidaEntity.isCalcComissServ());

        }
    }

    private void selecionarBox() {
        if (cbCaracDaOperação.getSelectedItem() == "Venda") {
            cbDiminuirEstoque.setSelected(true);
            cbEntraDinheiro.setSelected(true);
            cbCalcComissaoDeProd.setSelected(false);
            cbCalcComissaoDeServ.setSelected(false);

            cbDiminuirEstoque.setEnabled(true);
            cbEntraDinheiro.setEnabled(true);
            cbCalcComissaoDeProd.setEnabled(true);
            cbCalcComissaoDeServ.setEnabled(true);
        }
        if (cbCaracDaOperação.getSelectedItem() == "Pré Venda") {
            cbDiminuirEstoque.setSelected(true);
            cbEntraDinheiro.setSelected(true);
            cbCalcComissaoDeProd.setSelected(false);
            cbCalcComissaoDeServ.setSelected(false);

            cbDiminuirEstoque.setEnabled(true);
            cbEntraDinheiro.setEnabled(true);
            cbCalcComissaoDeProd.setEnabled(true);
            cbCalcComissaoDeServ.setEnabled(true);
        }
        if (cbCaracDaOperação.getSelectedItem() == "Ajuste de Saída") {
            cbDiminuirEstoque.setSelected(true);
            cbEntraDinheiro.setSelected(true);
            cbCalcComissaoDeProd.setSelected(false);
            cbCalcComissaoDeServ.setSelected(false);

            cbDiminuirEstoque.setEnabled(true);
            cbEntraDinheiro.setEnabled(true);
            cbCalcComissaoDeProd.setEnabled(true);
            cbCalcComissaoDeServ.setEnabled(true);
        }
        if (cbCaracDaOperação.getSelectedItem() == "Orçamento de Venda") {
            cbDiminuirEstoque.setSelected(false);
            cbEntraDinheiro.setSelected(false);
            cbCalcComissaoDeProd.setSelected(false);
            cbCalcComissaoDeServ.setSelected(false);

            cbDiminuirEstoque.setEnabled(false);
            cbEntraDinheiro.setEnabled(true);
            cbCalcComissaoDeProd.setEnabled(true);
            cbCalcComissaoDeServ.setEnabled(true);
        }
        if (cbCaracDaOperação.getSelectedItem() == "Saída Grátis") {
            cbDiminuirEstoque.setSelected(false);
            cbEntraDinheiro.setSelected(true);
            cbCalcComissaoDeProd.setSelected(false);
            cbCalcComissaoDeServ.setSelected(false);

            cbDiminuirEstoque.setEnabled(true);
            cbEntraDinheiro.setEnabled(true);
            cbCalcComissaoDeProd.setEnabled(true);
            cbCalcComissaoDeServ.setEnabled(true);
        }
    }

    private void salvarOperacao() {
        try {
            OperacaoDeSaidaDAO dao = new OperacaoDeSaidaDAO();
            if (dao.codigoExistente(Integer.parseInt(tfCodigo.getText())) == false) {
                OperacaoDeSaidaEntity oe = new OperacaoDeSaidaEntity();
                oe.setCodigo(Integer.parseInt(tfCodigo.getText()));
                oe.setNome(tfNome.getText());
                oe.setNaturezaDaOperacao(tfNaturezaDaOp.getText());
                oe.setCaracteristicaDeOperacao(cbCaracDaOperação.getSelectedItem().toString());

                oe.setDimEstq(cbDiminuirEstoque.isSelected());
                oe.setEntraDinheiro(cbEntraDinheiro.isSelected());
                oe.setCalcComissProd(cbCalcComissaoDeProd.isSelected());
                oe.setCalcComissServ(cbCalcComissaoDeServ.isSelected());

                dao.salvar(oe);
                alerta.mensagemConfirmacao("Operação cadastrada com sucesso!!!");
                limparCampos();
            } else {
                alerta.mensagemAviso("O código da operação já existe!!!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void alterarOperacao() {
        try {
            OperacaoDeSaidaDAO dao = new OperacaoDeSaidaDAO();
            OperacaoDeSaidaEntity oe = new OperacaoDeSaidaEntity();
            oe.setCodigo(Integer.parseInt(tfCodigo.getText()));
            oe.setNome(tfNome.getText());
            oe.setNaturezaDaOperacao(tfNaturezaDaOp.getText());
            oe.setCaracteristicaDeOperacao(cbCaracDaOperação.getSelectedItem().toString());
            oe.setDimEstq(cbDiminuirEstoque.isSelected());
            oe.setEntraDinheiro(cbEntraDinheiro.isSelected());
            oe.setCalcComissProd(cbCalcComissaoDeProd.isSelected());
            oe.setCalcComissServ(cbCalcComissaoDeServ.isSelected());
            oe.setId(this.operacaoDeSaidaEntity.getId());

            alerta.mensagemConfirmacao("Operação alterada com sucesso!!!");
            dao.alterar(oe);
            removerIdRemove();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void removerOperacao() throws SQLException {
        OperacaoDeSaidaDAO dao = new OperacaoDeSaidaDAO();
        alerta.mensagemAviso("A operação foi deletada com sucesso");
        dao.remover(operacaoDeSaidaEntity.getId());
        removerIdRemove();
    }

    private void removerBotao() {
        if (tfId.getText().equals("")) {
            bRemover.setVisible(false);
        }
        if (operacaoDeSaidaEntity.getId() != null) {
            tfCodigo.setEditable(false);
        }
        tfId.setVisible(false);
    }

    private void limparCampos() {
        tfNome.setText("");
        tfId.setText("");
        tfNaturezaDaOp.setText("");
        tfCodigo.setText("");

        cbCaracDaOperação.setSelectedItem("Venda");
        selecionarBox();
    }

    public void removerIdRemove() {
        operacaoDeSaidaEntity.setId(0);
        bRemover.setVisible(false);
        tfCodigo.setEditable(true);
    }

    private void limitarCampos() {
        tfNome.setDocument(new FixedLengthDocument(50));
        tfNaturezaDaOp.setDocument(new FixedLengthDocument(70));
    }
}
