/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.vconfiguracao;

import br.com.daruma.jna.DUAL;
import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.classes.CupomBematch;
import com.br.tecnomais.classes.CupomDaruma;
import com.br.tecnomais.classes.ImpressoraBematchEntity;
import com.br.tecnomais.classes.MP2032;
import com.br.tecnomais.classes.NovaData;
import com.br.tecnomais.dao.CupomDAO;
import com.br.tecnomais.dao.ImpressoraBematchDAO;
import com.br.tecnomais.dao.ImpressoraDarumaDAO;
import com.br.tecnomais.dao.ImpressoraPadraoDAO;
import com.br.tecnomais.entity.ClienteEntity;
import com.br.tecnomais.entity.CupomEntity;
import com.br.tecnomais.entity.ImpressoraDarumaEntity;
import com.br.tecnomais.entity.ProdutosVendaEntity;
import com.br.tecnomais.entity.VendaEntity;
import com.sun.jna.Native;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class CupomView extends javax.swing.JFrame {

    NovaData data = new NovaData();
    MP2032 dll = (MP2032) Native.loadLibrary("mp2032.dll", MP2032.class);
    CupomEntity ce = new CupomEntity();
    CupomDAO cDAO = new CupomDAO();
    ClienteEntity cli = new ClienteEntity();
    VendaEntity venda;
    List<ProdutosVendaEntity> prodList = new ArrayList();
    Double vlrTotal = 100000.0;

    ImpressoraPadraoDAO impressoraPadraoDAO = new ImpressoraPadraoDAO();
    ImpressoraBematchDAO impressoraBematchDAO = new ImpressoraBematchDAO();
    ImpressoraBematchEntity impressoraBematchEntity = new ImpressoraBematchEntity();
    ImpressoraDarumaDAO impressoraDarumaDAO = new ImpressoraDarumaDAO();
    ImpressoraDarumaEntity impressoraDarumaEntity = new ImpressoraDarumaEntity();
    String impressoraAtual = "";

    /**
     * Creates new form CupomView
     */
    public CupomView() {
        initComponents();
        retornaConf();
        try {
            impressoraAtual = impressoraPadraoDAO.retornaImpAtual();
            if (impressoraAtual.equals("ImpressoraDaruma")) {
                impressoraDarumaEntity = impressoraDarumaDAO.retornaIde();
                int tRetorno = DUAL.regTermica(impressoraDarumaEntity.getRegistroTermico());
                int pRetorno = DUAL.regPortaComunicacao(impressoraDarumaEntity.getPortaComunicacao());
                int pvRetorno = DUAL.regVelocidade(impressoraDarumaEntity.getPortaVelocidade());
                int cG2Retorno = DUAL.regLinhasGuilhotina(impressoraDarumaEntity.getTamanhoGuilhotina());
                int zRetorno = DUAL.regZeroCortado(impressoraDarumaEntity.getZeroCortadoStatus());

            } else if (impressoraAtual.equals("ImpressoraBematech")) {
                impressoraBematchEntity = impressoraBematchDAO.RetornImpBematchCfg();
                if (impressoraBematchEntity.getDll64() == 1) {
                    dll = (MP2032) Native.loadLibrary("mp2064.dll", MP2032.class);
                }
                dll.ConfiguraModeloImpressora(8);
                dll.IniciaPorta(impressoraBematchEntity.getPorta());
                dll.IniciaPorta("USB");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        adicionaInfCupom();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCabecalho = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfEndrecoTelefone = new javax.swing.JTextField();
        tfMensagemFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel1.setBackground(new java.awt.Color(170, 180, 180));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cupom");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);

        jLabel2.setText("Cabeçalho");

        tfCabecalho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCabecalhoFocusGained(evt);
            }
        });

        jLabel3.setText("Endereço/ Telefone");

        jLabel4.setText("Mensagem");

        jButton1.setText("Testar Impressão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfEndrecoTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addComponent(tfMensagemFinal)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfEndrecoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMensagemFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (impressoraAtual.equals("ImpressoraBematech")) {
            new CupomBematch(dll, venda, cli, ce, prodList, vlrTotal).imprimirCabecalhoBematechVendas();
        } else if (impressoraAtual.equals("ImpressoraDaruma")) {
            vlrTotal = 1000.0;
            new CupomDaruma(venda, cli, ce, impressoraDarumaEntity, prodList, vlrTotal)
                    .imprimirCabecalhoDaruma("150.0", data.dataAtual());
        }

//        dll.AjustaLarguraPapel(600);
//        dll.FormataTX(tfCabecalho.getText() + "\n", 2, 0, 0, 1, 1);
//        dll.FormataTX(tfEndrecoTelefone.getText() + "\n", 2, 0, 0, 0, 0);
////        dll.BematechTX("(88)3441-1256");
//        dll.BematechTX("--------------------------------------------------\n");
//        dll.BematechTX("Operacao: VENDA ESTADUAL" + "    Cupom: 103");
////        dll.BematechTX("Cupom: " + codigoVenda.toString());
//        dll.BematechTX("\nCaixa: CAIXA 1");
//        dll.BematechTX("   Data/Hora: 10/05/2016 11:10");
//        dll.BematechTX("\n       --------- DADOS DO CLIENTE ---------\n");
//
//        dll.BematechTX("Nome: Jose Farias das Silvas" + "\n");
//
//        dll.BematechTX("Endereco: Texeira de Freitas 90" + "\n");
//
//        dll.BematechTX("CPF: 053.099.168-85" + "\n");
//
//        dll.BematechTX("          ****** CUPOM NAO FISCAL ******\n");
//        dll.BematechTX("Descricao   Cod   Quant   PrecoUN   PrecoTotal\n");
//        dll.BematechTX("-------------------------------------------------\n");
//        dll.BematechTX("HD PC 1TB TOSHIBA - UN" + "\n" + 10 + "              " + "   " + 1 + "     R$300.00" + "   R$300.00" + "\n");
//        dll.BematechTX("----------------Resumo da Compra-----------------\n");
//        dll.FormataTX("D R$200.00 P R$100.00 ", 2, 0, 0, 0, 1);
//        dll.BematechTX("\n P x1 50.00 10/05/2016 P x2 50.00 10/06/2016");
//        dll.BematechTX("\nValor Total R$300.00 ");
////        dll.BematechTX("   Numero do Cupom: " + codigoVenda.toString());
//        dll.BematechTX("\n" + tfMensagemFinal.getText());
//        dll.AcionaGuilhotina(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.ce.getCabecalho() == null || this.ce.getCabecalho().equals("")) {
            salvar();
        } else {
            editar();
        }
        new Alertas().mensagemConfirmacao("Cupom salvo com sucesso!!!");
        retornaConf();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfCabecalhoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCabecalhoFocusGained

    }//GEN-LAST:event_tfCabecalhoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CupomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CupomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CupomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CupomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CupomView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfCabecalho;
    private javax.swing.JTextField tfEndrecoTelefone;
    private javax.swing.JTextField tfMensagemFinal;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        CupomEntity ce = new CupomEntity();
        ce.setCabecalho(tfCabecalho.getText());
        ce.setEndereco(tfEndrecoTelefone.getText());
        ce.setMensagem(tfMensagemFinal.getText());

        cDAO.save(ce);
    }

    private void editar() {
        CupomEntity ce = new CupomEntity();
        ce.setCabecalho(tfCabecalho.getText());
        ce.setEndereco(tfEndrecoTelefone.getText());
        ce.setMensagem(tfMensagemFinal.getText());
        cDAO.update(ce);
    }

    public void retornaConf() {
        try {
            this.ce = cDAO.retornaConfigsCupom();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void adicionaInfCupom() {
        tfEndrecoTelefone.setDocument(new FixedLengthDocument(50));
        tfEndrecoTelefone.setText(ce.getEndereco());
        tfCabecalho.setText(ce.getCabecalho());
        tfMensagemFinal.setText(ce.getMensagem());
        venda = new VendaEntity();
        venda.setCaixa("Caixa 1");
        venda.setClienteID(1);
        venda.setDataVenda(data.dataAtual());
        venda.setFormaPagamento("DINHEIRO");
        venda.setFormaPagamento2("PARCELADO");
        venda.setFormaPagamento3("CARTAO CREDITO");
        String hora = String.valueOf(new SimpleDateFormat("HH:mm").format(new Date(System.currentTimeMillis())));
        venda.setHora(hora);
        venda.setId(101);
        venda.setOperacao("VENDA ESTADUAL");
        venda.setParcelas(2);
        venda.setStatus("A");
        venda.setVendedor("Joao");
        venda.setVlrForma1(20000.0);
        venda.setVlrForma2(30000.0);
        venda.setVlrForma3(50000.0);
        venda.setVlrTotal(1000.0);

        cli.setNome("Carlos");
        cli.setCnpjOuCpf("123.456.789-10");
        cli.setEndereco("Rua Texeira de Freitas");
        cli.setId(1);
        ProdutosVendaEntity prt = new ProdutosVendaEntity();
        prt.setCodigoProduto(1);
        prt.setProdutoServico("HD PC 2TB TOSHIBA - UN");
        prt.setId(1);
        prt.setPrecoUnitario(50000.0);
        prt.setQuantidade(1.0);
        prt.setVendaID(1);
        prt.setPrecoTotal(50000.0);
        prodList.add(prt);
        prt = new ProdutosVendaEntity();
        prt.setCodigoProduto(2);
        prt.setProdutoServico("HD PC 1TB TOSHIBA - UN");
        prt.setId(2);
        prt.setPrecoUnitario(25000.0);
        prt.setQuantidade(2.0);
        prt.setVendaID(1);
        prt.setPrecoTotal(50000.0);
        prodList.add(prt);
    }
}
