/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.vconfiguracao;

import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.dao.ImpressoraDarumaDAO;
import com.br.tecnomais.entity.ImpressoraDarumaEntity;
import java.sql.SQLException;

/**
 *
 * @author Desenvolvimento
 */
public class ImpressoraDarumaView extends javax.swing.JFrame {

    ImpressoraDarumaDAO dao = new ImpressoraDarumaDAO();
    Alertas alerta = new Alertas();

    /**
     * Creates new form ImpressoraDarumaView
     */
    public ImpressoraDarumaView() {
        initComponents();
        tfId.setVisible(false);
        lbId.setVisible(false);
        try {
            configuracao();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfPortaComunicacao = new javax.swing.JTextField();
        tfVelocidadePorta = new javax.swing.JTextField();
        tfNsaltoLinhas = new javax.swing.JTextField();
        tfStatusGuilhotina = new javax.swing.JTextField();
        tfTamanhoGuilhotina = new javax.swing.JTextField();
        tfRegistroTermico = new javax.swing.JTextField();
        tfZeroCortado0 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel1.setBackground(new java.awt.Color(170, 180, 180));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configurações da Impressora Daruma Não-Fiscal");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);

        jLabel9.setText("Zero cortado Ø");

        lbId.setText("id");

        jLabel3.setText("Porta de Comunicação");

        jLabel4.setText("Velocidade da Porta");

        jLabel5.setText("N° Salto de Linhas");

        jLabel6.setText("Status da Guilhotina");

        jLabel7.setText("Tamanho da Guilhotina");

        jLabel8.setText("Registro Términco");

        tfId.setEditable(false);
        tfId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfPortaComunicacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfVelocidadePorta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfNsaltoLinhas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNsaltoLinhas.setText("0");
        tfNsaltoLinhas.setToolTipText("Número de salto de Linhas e tamanho da Guilhotina são acumuláveis");
        tfNsaltoLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNsaltoLinhasActionPerformed(evt);
            }
        });

        tfStatusGuilhotina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfStatusGuilhotina.setText("0");

        tfTamanhoGuilhotina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTamanhoGuilhotina.setText("0");
        tfTamanhoGuilhotina.setToolTipText("Número de salto de Linhas e tamanho da Guilhotina são acumuláveis");

        tfRegistroTermico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRegistroTermico.setText("1");

        tfZeroCortado0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfZeroCortado0.setText("0");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Valor entre 0 e 1");

        jLabel11.setText("Valor entre 0 e 1");

        jLabel12.setText("Valor entre 0 e 20");

        jLabel13.setText("Valor entre 0 e 1");

        jLabel14.setText("Valor entre 0 e 20");

        jLabel16.setText("Velocidade da Porta Ut");

        jLabel18.setText("Porta Utilizada");

        jLabel17.setText("Valores entre 0 e 1 são para ativar ou desativar as funções Ex: 0 = desativado, 1 = ativado");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/tecnomais/images/refresh icon.png"))); // NOI18N
        jButton2.setToolTipText("Recarregar configurações da impressora.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbId)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfVelocidadePorta)
                            .addComponent(tfNsaltoLinhas)
                            .addComponent(tfStatusGuilhotina)
                            .addComponent(tfTamanhoGuilhotina)
                            .addComponent(tfRegistroTermico)
                            .addComponent(tfZeroCortado0)
                            .addComponent(tfId)
                            .addComponent(tfPortaComunicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfId, tfNsaltoLinhas, tfPortaComunicacao, tfRegistroTermico, tfStatusGuilhotina, tfTamanhoGuilhotina, tfVelocidadePorta, tfZeroCortado0});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPortaComunicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfVelocidadePorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNsaltoLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfStatusGuilhotina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTamanhoGuilhotina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfRegistroTermico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfZeroCortado0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNsaltoLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNsaltoLinhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNsaltoLinhasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (!dao.verificaConfiguracaoExistente()) {
                salvar();
                alerta.mensagemConfirmacao("Nova configuração Daruma salva com sucesso!!!");
                configuracao();
            } else {
                alterar();
                alerta.mensagemConfirmacao("Configuração da Impressora Daruma foi alterada com sucesso!!!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       impressoraDarumaConfig();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpressoraDarumaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbId;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNsaltoLinhas;
    private javax.swing.JTextField tfPortaComunicacao;
    private javax.swing.JTextField tfRegistroTermico;
    private javax.swing.JTextField tfStatusGuilhotina;
    private javax.swing.JTextField tfTamanhoGuilhotina;
    private javax.swing.JTextField tfVelocidadePorta;
    private javax.swing.JTextField tfZeroCortado0;
    // End of variables declaration//GEN-END:variables

    private void salvar() throws SQLException {
        ImpressoraDarumaEntity ide = new ImpressoraDarumaEntity();
        ide.setNumSaltoLinhas(tfNsaltoLinhas.getText());
        ide.setPortaComunicacao(tfPortaComunicacao.getText());
        ide.setPortaVelocidade(tfVelocidadePorta.getText());
        ide.setRegistroTermico(tfRegistroTermico.getText());
        ide.setStatusGuilhotina(tfStatusGuilhotina.getText());
        ide.setTamanhoGuilhotina(tfTamanhoGuilhotina.getText());
        ide.setZeroCortadoStatus(tfZeroCortado0.getText());
        dao.salvar(ide);
    }

    private void alterar() throws SQLException {
        ImpressoraDarumaEntity ide = new ImpressoraDarumaEntity();
        ide.setId(Integer.parseInt(tfId.getText()));
        ide.setNumSaltoLinhas(tfNsaltoLinhas.getText());
        ide.setPortaComunicacao(tfPortaComunicacao.getText());
        ide.setPortaVelocidade(tfVelocidadePorta.getText());
        ide.setRegistroTermico(tfRegistroTermico.getText());
        ide.setStatusGuilhotina(tfStatusGuilhotina.getText());
        ide.setTamanhoGuilhotina(tfTamanhoGuilhotina.getText());
        ide.setZeroCortadoStatus(tfZeroCortado0.getText());
        dao.update(ide);
    }

    private void configuracao() throws SQLException {
        ImpressoraDarumaEntity ide = new ImpressoraDarumaEntity();
        ide = dao.retornaIde();
        if (ide.getId() == null) {
            tfId.setText("");
        } else {
            tfId.setText(ide.getId().toString());
        }

        tfNsaltoLinhas.setText(ide.getNumSaltoLinhas());
        tfPortaComunicacao.setText(ide.getPortaComunicacao());
        tfVelocidadePorta.setText(ide.getPortaVelocidade());
        tfRegistroTermico.setText(ide.getRegistroTermico());
        tfStatusGuilhotina.setText(ide.getStatusGuilhotina());
        tfTamanhoGuilhotina.setText(ide.getTamanhoGuilhotina());
        tfZeroCortado0.setText(ide.getZeroCortadoStatus());
    }

    private void impressoraDarumaConfig() {

    
    }
}
