/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.vconfiguracao;

import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.classes.ImpressoraBematchEntity;
import com.br.tecnomais.dao.ImpressoraBematchDAO;
import java.sql.SQLException;

/**
 *
 * @author Usuario
 */
public class ImpressoraBematechView extends javax.swing.JFrame {
    
    ImpressoraBematchDAO ibDAO = new ImpressoraBematchDAO();
    ImpressoraBematchEntity ibEntity = new ImpressoraBematchEntity();

    /**
     * Creates new form ImpressoraBematchView
     */
    public ImpressoraBematechView() {
        initComponents();
        tfId.setVisible(false);
        try {
            ibEntity = ibDAO.RetornImpBematchCfg();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        retornaCfg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbDll32 = new javax.swing.JCheckBox();
        cbGuilhotina = new javax.swing.JCheckBox();
        cbDll64 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        tfPorta = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel1.setBackground(new java.awt.Color(170, 180, 180));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configurações da Impressora Bematch Não-Fiscal");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);

        cbDll32.setBackground(new java.awt.Color(200, 210, 210));
        buttonGroup1.add(cbDll32);
        cbDll32.setText("DLL 32 Bits");
        cbDll32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDll32ActionPerformed(evt);
            }
        });

        cbGuilhotina.setBackground(new java.awt.Color(200, 210, 210));
        cbGuilhotina.setText("Guilhotina");

        cbDll64.setBackground(new java.awt.Color(200, 210, 210));
        buttonGroup1.add(cbDll64);
        cbDll64.setText("DLL 64 Bits");

        jLabel2.setText("Porta");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGuilhotina)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbDll32)
                            .addComponent(cbDll64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar)
                        .addGap(8, 8, 8)
                        .addComponent(btCancelar)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCancelar, btSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCancelar)
                            .addComponent(btSalvar))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDll32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDll64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGuilhotina)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbDll32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDll32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDll32ActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (tfId.getText().equals("0")) {// corrigir
            Salvar();
            new Alertas().mensagemConfirmacao("Configuração salvar com sucesso!");
        } else {
            Alterar();
            new Alertas().mensagemConfirmacao("Configuração alterada com sucesso!");
        }
        retornaCfg();
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImpressoraBematechView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImpressoraBematechView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImpressoraBematechView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImpressoraBematechView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpressoraBematechView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbDll32;
    private javax.swing.JCheckBox cbDll64;
    private javax.swing.JCheckBox cbGuilhotina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfPorta;
    // End of variables declaration//GEN-END:variables

    public void Salvar() {
        ImpressoraBematchEntity ibe = new ImpressoraBematchEntity();
        ibe.setDll32(0);
        ibe.setDll64(0);
        ibe.setGuilhotina(0);
        
        if (cbDll32.isSelected()) {
            ibe.setDll32(1);
        }
        if (cbDll64.isSelected()) {
            ibe.setDll64(1);
        }
        if (cbGuilhotina.isSelected()) {
            ibe.setGuilhotina(1);
        }
        ibe.setId(1);
        ibe.setPorta(tfPorta.getText());
        ibEntity = ibe;
        ibDAO.salvar(ibe);
    }
    
    public void Alterar() {
        ImpressoraBematchEntity ibe = new ImpressoraBematchEntity();
        ibe.setDll32(0);
        ibe.setDll64(0);
        ibe.setGuilhotina(0);
        
        if (cbDll32.isSelected()) {
            ibe.setDll32(1);
        }
        if (cbDll64.isSelected()) {
            ibe.setDll64(1);
        }
        if (cbGuilhotina.isSelected()) {
            ibe.setGuilhotina(1);
        }
        ibe.setId(1);
        ibe.setPorta(tfPorta.getText());
        ibEntity = ibe;
        ibDAO.update(ibe);
    }
    
    public void retornaCfg() {
        limpar();
        if (ibEntity.getDll32() == 1) {
            cbDll32.setSelected(true);
        }
        if (ibEntity.getDll64() == 1) {
            cbDll64.setSelected(true);
        }
        if (ibEntity.getGuilhotina() == 1) {
            cbGuilhotina.setSelected(true);
        }
        tfId.setText(ibEntity.getId().toString());
        tfPorta.setText(ibEntity.getPorta());
    }
    
    public void AdicionaCfg() {
        if (cbDll32.isSelected()) {
            ibEntity.setDll32(1);
        }
        if (cbDll64.isSelected()) {
            ibEntity.setDll64(1);
        }
        if (cbGuilhotina.isSelected()) {
            ibEntity.setGuilhotina(1);
        }
        ibEntity.setPorta(tfPorta.getText());
    }
    
    public void limpar() {    
        cbDll32.setSelected(false);
        cbDll64.setSelected(false);
        cbGuilhotina.setSelected(false);
        tfPorta.setText("");
    }
}
