/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.vconfiguracao;

import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.dao.ImpressoraPadraoDAO;
import com.br.tecnomais.entity.ImpressoraPadraoEntity;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;

/**
 *
 * @author Desenvolvimento
 */
public class SelecionaConfigImpressoraView extends javax.swing.JFrame {

    ImpressoraPadraoDAO dao = new ImpressoraPadraoDAO();
    Alertas alerta = new Alertas();

    /**
     * Creates new form SelecionaConfigImpressoraView
     */
    public SelecionaConfigImpressoraView() {
        initComponents();
        preencherJcomboBox();

        cbSem.setVisible(false);
        try {
            String impAtual = dao.retornaImpAtual();
            if (impAtual.equals("ImpressoraDaruma")) {
                cbDaruma.setSelected(true);
            } else if (impAtual.equals("ImpressoraBematech")) {
                cbBematch.setSelected(true);
            } else {
                cbSem.setSelected(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelecionaConfigImpressoraView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgImpressoraPadrao = new javax.swing.ButtonGroup();
        cbDaruma = new javax.swing.JCheckBox();
        cbBematch = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcImpressoras = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        cbSem = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbDaruma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDarumaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbDarumaMousePressed(evt);
            }
        });
        cbDaruma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDarumaActionPerformed(evt);
            }
        });

        cbBematch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBematchMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbBematchMousePressed(evt);
            }
        });
        cbBematch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBematchActionPerformed(evt);
            }
        });

        jLabel3.setText("Impressora Padrão");

        jButton1.setText("Impressora Daruma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Impressora Bematch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Impressoras Compativeis");

        jcImpressoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcImpressorasActionPerformed(evt);
            }
        });

        jButton3.setText("CUPOM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bgImpressoraPadrao.add(cbSem);
        cbSem.setToolTipText("Sem Impressora Selecionada");
        cbSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcImpressoras, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDaruma)
                            .addComponent(cbBematch)
                            .addComponent(cbSem))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(cbDaruma)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(cbBematch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(cbSem))
                .addGap(14, 14, 14)
                .addComponent(jcImpressoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbDarumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDarumaActionPerformed
        if (cbDaruma.isSelected()) {
            cbBematch.setSelected(false);
            ImpressoraPadraoEntity ipe = new ImpressoraPadraoEntity();
            ipe.setImpressoraAtual("ImpressoraDaruma");
            try {
                if (!dao.verificaConfiguracaoExistente()) {
                    dao.salvar(ipe);
                    //alerta.mensagemConfirmacao("Nova logomarca salva com sucesso!!!");
                } else {
                    dao.alterar(ipe);
                    // alerta.mensagemConfirmacao("Logomarca já existente foi alterada com sucesso!!!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cbDarumaActionPerformed

    private void cbBematchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBematchActionPerformed
        if (cbBematch.isSelected()) {
            cbDaruma.setSelected(false);
            ImpressoraPadraoEntity ipe = new ImpressoraPadraoEntity();
            ipe.setImpressoraAtual("ImpressoraBematech");
            try {
                if (!dao.verificaConfiguracaoExistente()) {
                    dao.salvar(ipe);
                } else {
                    dao.alterar(ipe);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cbBematchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ImpressoraDarumaView().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new ImpressoraBematechView().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new CupomView().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcImpressorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcImpressorasActionPerformed
        PrintService[] p = PrinterJob.lookupPrintServices();
        System.out.println("Porta: " + p[jcImpressoras.getSelectedIndex()].getName());
    }//GEN-LAST:event_jcImpressorasActionPerformed

    private void cbSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSemActionPerformed
        if (cbSem.isSelected()) {
            ImpressoraPadraoEntity ipe = new ImpressoraPadraoEntity();
            ipe.setImpressoraAtual("SemImpressora");
            try {
                if (!dao.verificaConfiguracaoExistente()) {
                    dao.salvar(ipe);
                } else {
                    dao.alterar(ipe);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cbSemActionPerformed

    private void cbDarumaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDarumaMousePressed
        if (evt.getClickCount() == 2 && evt.getClickCount() > 1) {
            cbDaruma.setSelected(false);
            ImpressoraPadraoEntity ipe = new ImpressoraPadraoEntity();
            ipe.setImpressoraAtual("SemImpressora");
            try {
                if (!dao.verificaConfiguracaoExistente()) {
                    dao.salvar(ipe);
                } else {
                    dao.alterar(ipe);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cbDarumaMousePressed

    private void cbBematchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBematchMousePressed

    }//GEN-LAST:event_cbBematchMousePressed

    private void cbBematchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBematchMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            cbBematch.setSelected(false);
            cbDaruma.setSelected(false);
            ImpressoraPadraoEntity ipe = new ImpressoraPadraoEntity();
            ipe.setImpressoraAtual("SemImpressora");
            try {
                if (!dao.verificaConfiguracaoExistente()) {
                    dao.salvar(ipe);
                } else {
                    dao.alterar(ipe);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            System.out.println("deu certoB");
        }


    }//GEN-LAST:event_cbBematchMouseClicked

    private void cbDarumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDarumaMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            cbBematch.setSelected(false);
            cbDaruma.setSelected(false);
            ImpressoraPadraoEntity ipe = new ImpressoraPadraoEntity();
            ipe.setImpressoraAtual("SemImpressora");
            try {
                if (!dao.verificaConfiguracaoExistente()) {
                    dao.salvar(ipe);
                } else {
                    dao.alterar(ipe);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            System.out.println("deu certoD");
        }
    }//GEN-LAST:event_cbDarumaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionaConfigImpressoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionaConfigImpressoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionaConfigImpressoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionaConfigImpressoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionaConfigImpressoraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgImpressoraPadrao;
    private javax.swing.JCheckBox cbBematch;
    private javax.swing.JCheckBox cbDaruma;
    private javax.swing.JCheckBox cbSem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jcImpressoras;
    // End of variables declaration//GEN-END:variables

    private void preencherJcomboBox() {
        for (PrintService p : PrinterJob.lookupPrintServices()) {
            System.out.println(p.getName());
            jcImpressoras.addItem(p.getName());
        }
    }

}
