/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.relatorios;

import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.classes.NovaData;
import com.br.tecnomais.dao.CaixaDAO;
import com.br.tecnomais.dao.LogomarcaDAO;
import com.br.tecnomais.db.ConectaBanco;
import com.br.tecnomais.entity.CaixaEntity;
import java.sql.SQLException;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class RelatorioCaixa extends javax.swing.JFrame {

    NovaData data = new NovaData();
    ConectaBanco con = new ConectaBanco();
    LogomarcaDAO dao = new LogomarcaDAO();
    String status = "F";

    /**
     * Creates new form RelatorioCaixa
     */
    public RelatorioCaixa() {
        initComponents();
        con.conectar();
        tfDtInicial.setText(data.dataAtual());
        tfDtFinal.setText(data.dataAtual());
        preencherComboCaixa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfDtInicial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDtFinal = new javax.swing.JFormattedTextField();
        cbCaixa = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        chbAberto = new javax.swing.JCheckBox();
        chbFechado = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cbOperacao = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel2.setBackground(new java.awt.Color(170, 180, 180));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Relatório de Caixa");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);

        jLabel1.setText("Data Inicial: ");

        try {
            tfDtInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDtInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDtInicialActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Final:");

        try {
            tfDtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDtFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDtFinalActionPerformed(evt);
            }
        });

        jButton1.setText("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chbAberto.setBackground(new java.awt.Color(200, 210, 210));
        chbAberto.setText("A");
        chbAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAbertoActionPerformed(evt);
            }
        });

        chbFechado.setBackground(new java.awt.Color(200, 210, 210));
        chbFechado.setSelected(true);
        chbFechado.setText("F");
        chbFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFechadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Status:");

        cbOperacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODAS", "VENDA ESTADUAL", "PRE-VENDA", "BRINDE" }));

        jLabel5.setText("Operação:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfDtFinal)
                    .addComponent(cbOperacao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDtInicial, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbCaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbAberto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbFechado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbAberto)
                    .addComponent(chbFechado)
                    .addComponent(jLabel4)
                    .addComponent(cbOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfDtInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDtInicialActionPerformed
        tfDtFinal.requestFocus();
        tfDtFinal.selectAll();
    }//GEN-LAST:event_tfDtInicialActionPerformed

    private void tfDtFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDtFinalActionPerformed

    }//GEN-LAST:event_tfDtFinalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LogomarcaDAO logoDAO = new LogomarcaDAO();
        String logomarca;
        try {
            logomarca = logoDAO.mostraLogomarca();
            if (logomarca.equals("") || logomarca.equals(null)) {
                logomarca = "fund03376branc99o9954120.jpg";
            }

            if (chbAberto.isSelected() && chbFechado.isSelected()) {
                geraRelatorioStatusAandF(logomarca);
            } else if (chbAberto.isSelected() || chbFechado.isSelected()) {
                geraRelatorioStatusAorF(logomarca);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chbAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAbertoActionPerformed

    }//GEN-LAST:event_chbAbertoActionPerformed

    private void chbFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFechadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbFechadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCaixa;
    private javax.swing.JComboBox cbOperacao;
    private javax.swing.JCheckBox chbAberto;
    private javax.swing.JCheckBox chbFechado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField tfDtFinal;
    private javax.swing.JFormattedTextField tfDtInicial;
    // End of variables declaration//GEN-END:variables

    private void preencherComboCaixa() {
        CaixaDAO cDAO = new CaixaDAO();
        try {
            for (CaixaEntity c : cDAO.listar("%")) {
                cbCaixa.addItem(c.getNome());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void geraRelatorioStatusAorF(String logomarca) {
        try {
            String dataI = tfDtInicial.getText();
            String dataF = tfDtFinal.getText();
            HashMap p = new HashMap();
            p.put("logomarca", "Logomarca/" + logomarca);
            p.put("dataInicial", tfDtInicial.getText());
            p.put("dataFinal", tfDtFinal.getText());
            p.put("caixa", cbCaixa.getSelectedItem().toString());

            if (cbOperacao.getSelectedIndex() == 0) {
                p.put("operacao", "%");
            } else {
                p.put("operacao", cbOperacao.getSelectedItem().toString());
            }
            if (chbAberto.isSelected()) {
                p.put("status", "A");
            } else {
                p.put("status", "F");
            }
            JasperPrint jp = JasperFillManager.fillReport("./relatorio/relatoriosCaixaVendaPorData.jasper", p, con.conn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            new Alertas().mensagemErro("Erro ao imprimir relatorio: \n" + e);
        }
    }

    private void geraRelatorioStatusAandF(String logomarca) {
        try {
            String dataI = tfDtInicial.getText();
            String dataF = tfDtFinal.getText();
            HashMap p = new HashMap();
            p.put("logomarca", "Logomarca/" + logomarca);
            p.put("dataInicial", tfDtInicial.getText());
            p.put("dataFinal", tfDtFinal.getText());
            p.put("caixa", cbCaixa.getSelectedItem().toString());
            if (cbOperacao.getSelectedIndex() == 0) {
                p.put("operacao", "%");
            } else {
                p.put("operacao", cbOperacao.getSelectedItem().toString());
            }
            JasperPrint jp = JasperFillManager.fillReport("./relatorio/relatoriosCaixaVendaPorData2.jasper", p, con.conn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            new Alertas().mensagemErro("Erro ao imprimir relatorio: \n" + e);
        }
    }

}
