/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.relatorios;

import com.br.tecnomais.classes.NovaData;
import com.br.tecnomais.dao.LogomarcaDAO;
import com.br.tecnomais.db.ConectaBanco;
import com.br.tecnomais.entity.UsuarioEntity;
import java.sql.SQLException;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class SaidasPorDataView extends javax.swing.JDialog {

    ConectaBanco conn = new ConectaBanco();
    UsuarioEntity u;
    NovaData data = new NovaData();
    ConectaBanco con = new ConectaBanco();
    LogomarcaDAO dao = new LogomarcaDAO();
    String tipo = "";

    /**
     * Creates new form EntradasPorData
     */
    public SaidasPorDataView(java.awt.Frame parent, boolean modal, String tipo) {
        super(parent, false);
        this.tipo = tipo;
        initComponents();
        con.conectar();
        data.dataAtual(tfDtInicial);
        data.dataAtual(tfDtFinal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfDtInicial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDtFinal = new javax.swing.JFormattedTextField();
        btGerarRelatorio = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel2.setBackground(new java.awt.Color(170, 180, 180));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Relatório de Saídas Por Data");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);

        jLabel1.setText("Data Inicial: ");

        try {
            tfDtInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDtInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDtInicialActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Final:");

        try {
            tfDtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDtFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDtFinalActionPerformed(evt);
            }
        });

        btGerarRelatorio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGerarRelatorio.setText("Gerar");
        btGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Aberto", "Finalizado" }));

        jLabel4.setText("Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbStatus, 0, 102, Short.MAX_VALUE)
                            .addComponent(tfDtFinal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarRelatorioActionPerformed
        try {
            String aux = dao.mostraLogomarca();
            String status = cbStatus.getSelectedItem().toString();
            if (status.equals("Todos")) {
                status = "";
            } else if (status.equals("Aberto")) {
                status = "A";
            } else {
                status = "F";
            }
        
            if (cbStatus.getSelectedIndex() == 0 && tipo.equals("s")) {
                ireport("./relatorio/todasSaidasSimplificadas.jasper", "logomarca", aux, "dataInicial", tfDtInicial.getText(), "dataFinal", tfDtFinal.getText(), "", "");
            } else if (cbStatus.getSelectedIndex() == 0 && tipo.equals("c")) {
                ireport("./relatorio/saidasPorDataCompleta.jasper", "logomarca", aux, "dataInicial", tfDtInicial.getText(), "dataFinal", tfDtFinal.getText(), "", "");
            } else if (tipo.equals("c")) {
                ireport("./relatorio/saidasPorDataStatusCompleta.jasper", "logomarca", aux, "dataInicial", tfDtInicial.getText(), "dataFinal", tfDtFinal.getText(), "status", status);
            } else if (tipo.equals("s")) {
                ireport("./relatorio/saidasPorDataStatusSimplificada.jasper", "logomarca", aux, "dataInicial", tfDtInicial.getText(), "dataFinal", tfDtFinal.getText(), "status", status);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btGerarRelatorioActionPerformed

    private void tfDtInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDtInicialActionPerformed
        tfDtFinal.requestFocus();
        tfDtFinal.selectAll();
    }//GEN-LAST:event_tfDtInicialActionPerformed

    private void tfDtFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDtFinalActionPerformed
        btGerarRelatorio.requestFocus();
    }//GEN-LAST:event_tfDtFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidasPorDataView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidasPorDataView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidasPorDataView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidasPorDataView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaidasPorDataView dialog = new SaidasPorDataView(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerarRelatorio;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField tfDtFinal;
    private javax.swing.JFormattedTextField tfDtInicial;
    // End of variables declaration//GEN-END:variables

    private void gerarRelatorio(int id) throws JRException, SQLException {
        HashMap parametros = new HashMap();

        LogomarcaDAO dao = new LogomarcaDAO();
        String aux = dao.mostraLogomarca();
        if (aux == null || aux == "") {
            parametros.put("logomarca", "Logomarca/fund03376branc99o9954120.jpg");
        } else {
            parametros.put("logomarca", "Logomarca/" + aux);
        }

        parametros.put("clienteEspecifico", id);
        JasperPrint jp = JasperFillManager.fillReport("./relatorio/clienteEspecifico.jasper", parametros, conn.conn);
        JasperViewer jrv = new JasperViewer(jp, false);
        jrv.setVisible(true);
    }

    public void ireport(String caminho, String param1, String param11, String param2, String param22, String param3, String param33, String param4, String param44) {
        try {
            System.out.println(param11);
            HashMap parametros = new HashMap();
            if (param11 == null || param11 == "") {
                parametros.put(param1, "Logomarca/fund03376branc99o9954120.jpg");
                parametros.put(param2, param22);
            } else {
                parametros.put(param1, "Logomarca/" + param11);
                parametros.put(param2, param22);
            }
            parametros.put(param3, param33);
            parametros.put(param4, param44);

            JasperPrint jp;
            jp = JasperFillManager.fillReport(caminho, parametros, con.conn);
            JasperViewer jrv = new JasperViewer(jp, false);//segundo paremetro fechar ou não programa
            jrv.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ireport2(String caminho, String param1, String param11) {
        try {
            System.out.println(param11);
            HashMap parametros = new HashMap();
            if (param11 == null || param11 == "") {
                parametros.put(param1, "Logomarca/fund03376branc99o9954120.jpg");
                parametros.put("dataInicial", tfDtInicial.getText());
            } else {
                parametros.put(param1, "Logomarca/" + param11);
                parametros.put("dataInicial", tfDtInicial.getText());
            }
            parametros.put("dataFinal", tfDtFinal.getText());
            parametros.put("status", "A");

            JasperPrint jp;
            jp = JasperFillManager.fillReport(caminho, parametros, con.conn);
            JasperViewer jrv = new JasperViewer(jp, false);//segundo paremetro fechar ou não programa
            jrv.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
