/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.tecnomais.vmovimentacao;

import com.br.tecnomais.classes.Alertas;
import com.br.tecnomais.dao.ContaPagarDAO;
import com.br.tecnomais.entity.ContasPagarEntity;
import com.br.tecnomais.entity.PermissoesEntity;
import com.br.tecnomais.entity.UsuarioEntity;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ContaPagarListView extends javax.swing.JFrame {

    private final ContaPagarDAO dao = new ContaPagarDAO();
    UsuarioEntity u;
    PermissoesEntity p;

    /**
     * Creates new form ContaPagarListView
     */
    public ContaPagarListView(UsuarioEntity u, PermissoesEntity p) {
        this.u = u;
        this.p = p;
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        ajustarTabela();
        preencherTabela();
        bSelecionar.setText("Retornar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContasPagar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTipoCobranca = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfDataVencimento = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDataPagamento = new javax.swing.JFormattedTextField();
        tfDescricaoObs = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfContaId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfEntradaId = new javax.swing.JTextField();
        bSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 210, 210));

        jLabel1.setBackground(new java.awt.Color(170, 180, 180));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contas a Pagar");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);

        tbContasPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Valor a Pagar", "Fornecedor", "Pagamento", "Obs", "Data Vencimento"
            }
        ));
        tbContasPagar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tbContasPagarAncestorRemoved(evt);
            }
        });
        tbContasPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbContasPagarMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbContasPagar);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fornecedor");

        tfFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFornecedorFocusGained(evt);
            }
        });
        tfFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFornecedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Cobrança");

        cbTipoCobranca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "DINHEIRO", "PRAZO", "BOLETO", "CARTAO CREDITO", "CARTAO DEBITO", "CHEQUE" }));
        cbTipoCobranca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbTipoCobrancaKeyPressed(evt);
            }
        });

        jLabel5.setText("Usuário");

        tfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsuarioFocusGained(evt);
            }
        });

        jLabel6.setText("Vencimento");

        try {
            tfDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataVencimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDataVencimentoFocusLost(evt);
            }
        });
        tfDataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataVencimentoActionPerformed(evt);
            }
        });

        jLabel7.setText("Data de Emissão");

        jLabel2.setText("Descrição");

        try {
            tfDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataPagamentoActionPerformed(evt);
            }
        });

        tfDescricaoObs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDescricaoObsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDescricaoObsFocusLost(evt);
            }
        });
        tfDescricaoObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescricaoObsActionPerformed(evt);
            }
        });

        jLabel8.setText("Conta ID");

        tfContaId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfContaIdFocusGained(evt);
            }
        });

        jLabel9.setText("Entrada ID");

        tfEntradaId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEntradaIdFocusGained(evt);
            }
        });

        bSelecionar.setText("Selecionar");
        bSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(tfContaId)
                    .addComponent(jLabel9)
                    .addComponent(tfEntradaId, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(tfDescricaoObs)
                    .addComponent(jLabel3)
                    .addComponent(tfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(tfUsuario)
                            .addComponent(cbTipoCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDataVencimento)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(bSelecionar))))
                .addContainerGap(264, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bSelecionar, jButton1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescricaoObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(tfContaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEntradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSelecionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tbContasPagar.clearSelection();
        bSelecionar.setText("Retornar");
        if (tfContaId.getText().isEmpty() && tfDataPagamento.getText().contains(" ")
                && tfDataVencimento.getText().contains(" ") && tfDescricaoObs.getText().isEmpty()
                && tfEntradaId.getText().isEmpty() && tfFornecedor.getText().isEmpty()
                && tfUsuario.getText().isEmpty() && cbTipoCobranca.getSelectedItem().toString().equals("...")) {
            preencherTabela();
        } else {
            pesquisar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFornecedorActionPerformed
        pesquisar();
    }//GEN-LAST:event_tfFornecedorActionPerformed

    private void cbTipoCobrancaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbTipoCobrancaKeyPressed
        pesquisar();
    }//GEN-LAST:event_cbTipoCobrancaKeyPressed

    private void tfDataVencimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDataVencimentoFocusLost
        if (tfDataVencimento.getText().equals(" ")) {
            tfDataVencimento.setValue("");
        }
    }//GEN-LAST:event_tfDataVencimentoFocusLost

    private void tfDataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataVencimentoActionPerformed
        pesquisar();
    }//GEN-LAST:event_tfDataVencimentoActionPerformed

    private void tfDataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataPagamentoActionPerformed
        pesquisar();
    }//GEN-LAST:event_tfDataPagamentoActionPerformed

    private void tfDescricaoObsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescricaoObsFocusLost

    }//GEN-LAST:event_tfDescricaoObsFocusLost

    private void tfDescricaoObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescricaoObsActionPerformed
        pesquisar();
    }//GEN-LAST:event_tfDescricaoObsActionPerformed

    private void bSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelecionarActionPerformed
        if (bSelecionar.getText().equals("Retornar")) {
            this.dispose();
            new ContasApagar(0, u, p).setVisible(true);
        } else {
            int linha = tbContasPagar.getSelectedRow();
            int id = Integer.parseInt(tbContasPagar.getValueAt(linha, 0).toString());
            if (id > 0) {
                this.dispose();
                new ContasApagar(id, u, p).setVisible(true);
            }
        }
    }//GEN-LAST:event_bSelecionarActionPerformed

    private void tbContasPagarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContasPagarMousePressed
        bSelecionar.setText("Selecionar");
    }//GEN-LAST:event_tbContasPagarMousePressed

    private void tfContaIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfContaIdFocusGained
//        tbContasPagar.clearSelection();
    }//GEN-LAST:event_tfContaIdFocusGained

    private void tfDescricaoObsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescricaoObsFocusGained
//        tbContasPagar.clearSelection();
    }//GEN-LAST:event_tfDescricaoObsFocusGained

    private void tfEntradaIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEntradaIdFocusGained
//       tbContasPagar.clearSelection();
    }//GEN-LAST:event_tfEntradaIdFocusGained

    private void tfFornecedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFornecedorFocusGained
        //      tbContasPagar.clearSelection();
    }//GEN-LAST:event_tfFornecedorFocusGained

    private void tfUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsuarioFocusGained
        //        tbContasPagar.clearSelection();
    }//GEN-LAST:event_tfUsuarioFocusGained

    private void tbContasPagarAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbContasPagarAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbContasPagarAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaPagarListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaPagarListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaPagarListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaPagarListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaPagarListView(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSelecionar;
    private javax.swing.JComboBox cbTipoCobranca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbContasPagar;
    private javax.swing.JTextField tfContaId;
    private javax.swing.JFormattedTextField tfDataPagamento;
    private javax.swing.JFormattedTextField tfDataVencimento;
    private javax.swing.JTextField tfDescricaoObs;
    private javax.swing.JTextField tfEntradaId;
    private javax.swing.JTextField tfFornecedor;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {
        DefaultTableModel tb = (DefaultTableModel) tbContasPagar.getModel();
        tb.setNumRows(0);
        try {
            for (ContasPagarEntity c : dao.listaContasPagar()) {
                tb.addRow(new Object[]{c.getContaId(), c.getDescricao(), new DecimalFormat("0.00").format(c.getVlrPagar() / 100), c.getFornecedor(), c.getTipoCobranca(), c.getObs(), c.getDataVencimento(), c.getUsuario(), c.getDataEmissao(), c.getEntradaId()});
            }
        } catch (Exception e) {
            new Alertas().mensagemErro("Erro ao executar a sql para preencher a tabela!" + e);
        }
    }

    private void pesquisar() {
        List<ContasPagarEntity> minhaLista = new ArrayList<>();
        String descricao = "";
        String tipoCobranca = "";
        String dataVencimento = "";
        String fornecedor = "";
        String usuario = "";
        String dataPagamento = "";
        String obs = "";

        if (tfContaId.getText().isEmpty() && tfEntradaId.getText().isEmpty()) {
            if (!tfDescricaoObs.getText().isEmpty()) {
                descricao = tfDescricaoObs.getText();
            }

            if (!cbTipoCobranca.getSelectedItem().toString().equals("...")) {
                tipoCobranca = cbTipoCobranca.getSelectedItem().toString();
            }

            if (!tfDataVencimento.getText().contains(" ")) {
                dataVencimento = tfDataVencimento.getText();
            }

            if (!tfFornecedor.getText().isEmpty()) {
                fornecedor = tfFornecedor.getText();
            }

            if (!tfUsuario.getText().isEmpty()) {
                usuario = tfUsuario.getText();
            }
//
            if (!tfDataPagamento.getText().contains(" ")) {
                dataPagamento = tfDataPagamento.getText();
            }

            try {
                minhaLista = dao.listaContasPagarFiltros("%" + descricao + "%", "%" + tipoCobranca + "%", "%" + dataVencimento + "%", "%" + fornecedor + "%", "%" + usuario + "%", "%" + dataPagamento + "%", "%" + obs + "%");
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        } else {
            try {
                if (!tfContaId.getText().isEmpty() && tfEntradaId.getText().isEmpty()) {
                    minhaLista = dao.contasPagarList(Integer.parseInt(tfContaId.getText()));
                }
                if (tfContaId.getText().isEmpty() && !tfEntradaId.getText().isEmpty()) {
                    minhaLista = dao.contasPagarListEntradaID(Integer.parseInt(tfEntradaId.getText()));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        DefaultTableModel tb = (DefaultTableModel) tbContasPagar.getModel();
        tb.setNumRows(0);
        try {
            for (ContasPagarEntity c : minhaLista) {
                tb.addRow(new Object[]{c.getContaId(), c.getDescricao(), new DecimalFormat("0.00").format(c.getVlrPagar() / 100), c.getFornecedor(), c.getTipoCobranca(), c.getObs(), c.getDataVencimento(), c.getUsuario(), c.getDataEmissao(), c.getEntradaId()});
//                System.out.println("ID: " + c.getContasPagasId() + " Entrada: " + c.getEntradaId());
            }
        } catch (Exception e) {
            new Alertas().mensagemErro("Erro ao executar a sql para preencher a tabela!");
        }
    }

    private void ajustarTabela() {
        tbContasPagar.getColumnModel().getColumn(0).setMinWidth(0);
        tbContasPagar.getColumnModel().getColumn(0).setPreferredWidth(80);
        tbContasPagar.getColumnModel().getColumn(0).setMaxWidth(100);
        tbContasPagar.getColumnModel().getColumn(1).setMinWidth(0);
        tbContasPagar.getColumnModel().getColumn(1).setPreferredWidth(290);
        tbContasPagar.getColumnModel().getColumn(1).setMaxWidth(300);
        tbContasPagar.getColumnModel().getColumn(2).setMinWidth(0);
        tbContasPagar.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbContasPagar.getColumnModel().getColumn(2).setMaxWidth(150);
        tbContasPagar.getColumnModel().getColumn(3).setMinWidth(0);
        tbContasPagar.getColumnModel().getColumn(3).setPreferredWidth(190);
        tbContasPagar.getColumnModel().getColumn(3).setMaxWidth(240);
        tbContasPagar.getColumnModel().getColumn(4).setMinWidth(0);
        tbContasPagar.getColumnModel().getColumn(4).setPreferredWidth(120);
        tbContasPagar.getColumnModel().getColumn(4).setMaxWidth(200);
        tbContasPagar.getColumnModel().getColumn(6).setMinWidth(0);
        tbContasPagar.getColumnModel().getColumn(6).setPreferredWidth(80);
        tbContasPagar.getColumnModel().getColumn(6).setMaxWidth(90);
//        tbContasPagar.getColumnModel().getColumn(6).setMinWidth(0);
//        tbContasPagar.getColumnModel().getColumn(6).setPreferredWidth(0);
//        tbContasPagar.getColumnModel().getColumn(6).setMaxWidth(0);
    }
}
